const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync}=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const source=n=>readFileSync(path.join(root,'static',n),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,30));
const opportunities=[{id:11,title:'Première exposition',city:'Paris',summary:'Un premier contexte'},{id:22,title:'Deuxième exposition',city:'Lyon',summary:'Un deuxième contexte'}];
function setup(){
 const requests=[],errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/Not implemented|Could not parse CSS/.test(e.message))errors.push(e)});
 const dom=new JSDOM(source('plugart_v162.html'),{url:'http://plugart.test/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window;
 w.HTMLElement.prototype.scrollTo=function(){};w.TextDecoder=TextDecoder;w.TextEncoder=TextEncoder;
 w.fetch=async(url,opt={})=>{requests.push({url:String(url),opt});if(String(url).includes('/api/opportunities'))return new Response(JSON.stringify(opportunities));if(String(url).includes('dashboard-bootstrap'))return new Response(JSON.stringify({opportunities,stats:{opportunities:2,events:46,drafts:1,urgent:0}}));if(String(url).includes('/api/v108/drafts'))return new Response(JSON.stringify([{id:9,kind:'carousel',title:'Brouillon',payload:{slides:[{title:'À reprendre',body:'Texte conservé'}]}}]));if(String(url).includes('/media'))return new Response('image',{headers:{'X-PLUG-Image-Fallback':'opportunity-v201'}});return new Response(JSON.stringify([]))};
 w.eval(source('plugart_v202_boot.js'));w.eval(source('plugart_v200.js'));
 w.document.head.appendChild(Object.assign(w.document.createElement('style'),{textContent:source('plugart_v200.css')}));
 return {dom,w,requests,errors};
}
test('first dashboard stays light; refresh bypasses the session snapshot',async()=>{const {dom,w,requests}=setup();try{await tick();assert.equal(requests.filter(x=>x.url==='/api/opportunities').length,0);assert.equal(w.document.querySelector('#v200Signals').textContent.includes('46'),true);assert.equal(w.getComputedStyle(w.document.querySelector('#searchOverlay')).display,'none');assert.equal(w.getComputedStyle(w.document.querySelector('#newOverlay')).display,'none');w.document.querySelector('#refreshData').click();await tick();assert.equal(requests.filter(x=>x.url.includes('dashboard-bootstrap')).length,2);assert.equal(requests.filter(x=>x.url.includes('plugart_v162.js')).length,0)}finally{dom.window.close()}});
test('free brief detaches the source and preserves the second opportunity',async()=>{const {dom,w}=setup();try{await tick();await w.PLUGART_V202_ROUTE('creation');await w.PLUGART_V200.seedOpportunity(22);const select=w.document.querySelector('#c200Source');select.value='';select.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelector('#c200Name').value,'Deuxième exposition');assert.equal(w.PLUGART_V200.snapshot().source_opportunity_id,'')}finally{dom.window.close()}});
test('import, slide editing and draft restore retain the visible editor state',async()=>{const {dom,w}=setup();try{await tick();w.PLUGART_V200.importSource({title:'Idée culturelle',body:'Texte de mon idée'},'idea');assert.equal(w.document.querySelector('#c200Brief').value,'Texte de mon idée');const slides=Array.from({length:5},(_,i)=>({title:'Page '+(i+1),body:'Texte '+i}));w.PLUGART_V200.importSlides(slides,{caption:'Une légende'});const articles=w.document.querySelectorAll('.c200-slide');assert.equal(articles.length,5);assert.equal(w.document.querySelectorAll('.c200-slide-bg').length,5);assert.deepEqual(Array.from(articles).map(a=>a.dataset.slide),['0','1','2','3','4']);const title=articles[3].querySelector('[data-edit="title"]');title.textContent='Modification conservée';title.dispatchEvent(new w.Event('input',{bubbles:true}));let snapshot=w.PLUGART_V200.snapshot();assert.equal(snapshot.payload.slides[3].title,'Modification conservée');w.PLUGART_V200.importDraft({...snapshot,id:72});assert.equal(w.document.querySelectorAll('.c200-slide')[3].querySelector('[data-edit="title"]').textContent,'Modification conservée');assert.equal(w.document.querySelector('#c200Legend').textContent,'Une légende')}finally{dom.window.close()}});
test('loaded advanced route is delegated on every dashboard shortcut',async()=>{const {dom,w}=setup();try{await tick();w.__PLUGART_LEGACY_READY=true;const routes=[];w.PLUGART_ROUTE=async function(r){routes.push(r)};await w.PLUGART_V202_ROUTE('radar');await w.PLUGART_V202_ROUTE('dashboard');w.document.querySelector('.v202-overview-actions [data-v200-go="bureau"]').click();await tick();assert.deepEqual(routes,['radar','dashboard','bureau']);assert.equal(w.document.querySelector('#plugyContext').textContent,'Contexte : Bureau')}finally{dom.window.close()}});
test('closed drawer is removed from keyboard navigation',async()=>{const {dom,w}=setup();try{await tick();const drawer=w.document.querySelector('#plugyDrawer');drawer.classList.add('open');await tick();assert.equal(drawer.getAttribute('aria-hidden'),'false');drawer.classList.remove('open');await tick();assert.equal(drawer.getAttribute('aria-hidden'),'true');assert.equal(drawer.inert,true)}finally{dom.window.close()}});
test('streamed copy appears before image completion; partial image results are explicit',async()=>{const {dom,w}=setup();try{await tick();await w.PLUGART_V202_ROUTE('creation');w.document.querySelector('#c200Name').value='Exposition test';let finish;const held=new Promise(r=>finish=r),enc=new TextEncoder();let release;
 w.fetch=async(url,opt={})=>{if(url.includes('/plugy/stream'))return new Response(new ReadableStream({start(controller){controller.enqueue(enc.encode(JSON.stringify({type:'delta',delta:'{"slides":[{"kicker":"TEST","title":"Texte progressif","body":"Visible avant les images"}'})+'\n'));release=()=>{controller.enqueue(enc.encode(JSON.stringify({type:'delta',delta:'],"caption":"Légende"}'})+'\n'+JSON.stringify({type:'done',model:'test'})+'\n'));controller.close()}}}));if(url.includes('/content/image')){await held;return new Response(JSON.stringify({url:'/api/v201/visual-fallback?label=Test',fallback:true}))}return new Response(JSON.stringify([]))};
const running=w.PLUGART_V200.generateCampaign();await tick();assert.match(w.document.querySelector('#c200Carousel').textContent,/Texte progressif/);assert.equal(w.document.querySelector('#c200Generate').disabled,true);release();finish();await running;assert.match(w.document.querySelector('#c200Status').textContent,/0 image\(s\) IA · 3 secours/);assert.match(w.document.querySelector('#c200MediaNote').textContent,/secours/)}finally{dom.window.close()}});
test('provider fallback leaves five editable slides and preserves the source image',async()=>{const {dom,w}=setup();try{await tick();await w.PLUGART_V202_ROUTE('creation');w.PLUGART_V200.importDraft({title:'Exposition source',payload:{facts:{name:'Exposition source',place:'Paris',brief:'Le contexte fourni'},visuals:['/api/v179/generated/source.webp'],visualMeta:{'/api/v179/generated/source.webp':{kind:'source',fallback:false}}}});w.fetch=async url=>url.includes('/plugy/stream')?new Response(JSON.stringify({type:'delta',delta:'Mode secours'})+'\n'+JSON.stringify({type:'done',model:'local',fallback:true})+'\n'):new Response(JSON.stringify({url:'/api/v201/visual-fallback?label=Test',fallback:true}));await w.PLUGART_V200.generateCampaign();const snap=w.PLUGART_V200.snapshot();assert.equal(snap.payload.slides.length,5);assert.equal(snap.payload.slides[0].title,'Exposition source');assert.equal(snap.payload.slides[1].body,'Le contexte fourni');assert.deepEqual(Array.from(snap.payload.visuals),['/api/v179/generated/source.webp']);assert.match(w.document.querySelector('#c200Status').textContent,/IA texte indisponible.*modèle local/);const title=w.document.querySelector('[data-slide="2"] [data-edit="title"]');title.textContent='Angle complété';title.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.PLUGART_V200.snapshot().payload.slides[2].title,'Angle complété')}finally{dom.window.close()}});
